#!/bin/bash

docker exec -it php8 bash -c 'cd ./socialnetwork/cabinet && php artisan serve --host=0.0.0.0 --port=8000'
# docker exec -it php8 bash -c 'cd ./socialnetwork/cabinet && npm run dev'
#docker exec -it php8 bash -c 'cd ./socialnetwork/cabinet'
